version: "3"
services:
  wireguard:
    build: wireguard/.
    # dockerfile: Dockerfile
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=8.8.8.8 #optional
      - INTERNAL_SUBNET=10.0.0.0/18 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      #- PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - data:/config
      - /lib/modules:/lib/modules #optional
    networks:
      net:
        ipv4_address: 192.168.240.2
    ports:
      - 51820:51820/udp
      - 8001:8001
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  vpn_api:
    build: vpn_api/.
    container_name: vpn_api
    volumes:
      - data:/config
    networks:
      net:
        ipv4_address: 192.168.240.3
    ports:
      - 8000:8000

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/wireguard_alpine/config

networks:
  net:
    driver: bridge  
    ipam:
      config:
        - subnet: 192.168.240.0/24
  